import { registerField, RegisterForm } from '@models';

export const DYNAMIC_FIELD_DATA_DEFAULT: registerField = {
  label_name: `Campo`,
  field_name: `campo`,
  placeholder: `Campo`,
  type: 'input',
  type_input: 'text',
  required: true,
  readonly: false,
  disabled: false,
  maxlength: 50,
  minlength: 3,
  min: 0,
  max: 100,
  step: 1,
  pattern: '',
  autofocus: false,
  autocomplete: 'on',
  multiple: false,
  size: 20,
  alt: '',
  rows: 1,
  cols: 1,
  wrap: 'soft',
  options: [],
  validations: [],
};

export const DYNAMIC_FORM_DATA_DEFAULT: RegisterForm = {
  meeting_id: 3,
  name: 'Formulario de registro',
  description: 'Descripción del formulario',
  view: 'register',
  fields: [
    {
      label_name: `Nombre completo`,
      field_name: `campo_nombre`,
      placeholder: `Nombres`,
      type: 'input',
      type_input: 'text',
      required: true,
      readonly: false,
      disabled: false,
      maxlength: 100,
      minlength: 3,
      min: 0,
      max: 0,
      step: 1,
      pattern: '',
      autofocus: false,
      autocomplete: 'off',
      multiple: false,
      size: 100,
      alt: '',
      rows: 1,
      cols: 1,
      wrap: 'soft',
      options: [],
      validations: [],
    },
    {
      label_name: `Tipo de identificación`,
      field_name: `tipo_identificacion`,
      placeholder: `Tipo de identificación`,
      type: 'select',
      type_input: 'text',
      required: true,
      readonly: false,
      disabled: false,
      maxlength: 0,
      minlength: 0,
      min: 99999,
      max: 999999999999,
      step: 1,
      pattern: '',
      autofocus: false,
      autocomplete: 'off',
      multiple: false,
      size: 100,
      alt: '',
      rows: 1,
      cols: 1,
      wrap: 'soft',
      options: [
        {
          label: 'Cédula de ciudadanía',
          value: 'CC',
          selected: true,
          disabled: false,
        },
        {
          label: 'Tarjeta de identidad',
          value: 'TI',
          selected: false,
          disabled: false,
        },
        {
          label: 'Cédula de extranjería',
          value: 'CE',
          selected: false,
          disabled: false,
        },
        {
          label: 'Registro civil',
          value: 'RC',
          selected: false,
          disabled: false,
        },
        {
          label: 'Número de pasaporte',
          value: 'PA',
          selected: false,
          disabled: false,
        },
        {
          label: 'Permiso especial de permanencia',
          value: 'PEP',
          selected: false,
          disabled: false,
        },
        {
          label: 'Documento de identificación extranjero',
          value: 'DIE',
          selected: false,
          disabled: false,
        },
        {
          label: 'Número único de identificación personal',
          value: 'NUIP',
          selected: false,
          disabled: false,
        },
        {
          label: 'Número de identificación tributaria',
          value: 'NIT',
          selected: false,
          disabled: false,
        },
        {
          label: 'Salvoconducto de permanencia',
          value: 'SP',
          selected: false,
          disabled: false,
        },
      ],
      validations: [],
    },
    {
      label_name: `Número de identificación`,
      field_name: `campo_identificacion`,
      placeholder: `Identificación`,
      type: 'input',
      type_input: 'text',
      required: true,
      readonly: false,
      disabled: false,
      maxlength: 5,
      minlength: 50,
      min: 0,
      max: 0,
      step: 1,
      pattern: '',
      autofocus: false,
      autocomplete: 'off',
      multiple: false,
      size: 100,
      alt: '',
      rows: 1,
      cols: 1,
      wrap: 'soft',
      options: [],
      validations: [],
    },
  ],
};